/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p47.reto4.vista;

//import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import utp.misiontic2022.c2.p47.reto4.controlador.ControladorRequerimientos;

/**
 *
 * @author NELSY MIRAMAG
 */
public class Requerimientos_GUI extends javax.swing.JFrame {

    private ControladorRequerimientos controlador;
    private Requerimiento1_TM reque1_TM;
    private Requerimiento2_TM reque2_TM;
    private Requerimiento3_TM reque3_TM;
    /**
     * Creates new form Requerimientos_GUI
     */
    public Requerimientos_GUI() {
        controlador = new ControladorRequerimientos();
        initComponents();
        ListarRegistros1();
        ListarRegistros2();
        ListarRegistros3();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        pReque1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros1 = new javax.swing.JTable();
        pReque2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegistros2 = new javax.swing.JTable();
        pReque3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRegistros3 = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Ventanas = new javax.swing.JMenu();
        Requerimiento1 = new javax.swing.JMenuItem();
        Requerimiento2 = new javax.swing.JMenuItem();
        Requerimiento3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 5 p47");
        setMinimumSize(new java.awt.Dimension(700, 300));

        pReque1.setName("Requerimiento1"); // NOI18N
        pReque1.setLayout(new java.awt.BorderLayout());

        tblRegistros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tblRegistros1);

        pReque1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Requerimiento1", pReque1);

        pReque2.setLayout(new java.awt.BorderLayout());

        tblRegistros2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tblRegistros2);

        pReque2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Requerimiento2", pReque2);

        pReque3.setLayout(new java.awt.BorderLayout());

        tblRegistros3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblRegistros3);

        pReque3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Requerimiento3", pReque3);

        getContentPane().add(tpPrincipal, java.awt.BorderLayout.CENTER);

        Archivo.setText("Archivo");

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Salir.setLabel("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        MenuBar.add(Archivo);

        Ventanas.setText("Ventanas");

        Requerimiento1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Requerimiento1.setLabel("Requerimiento1");
        Requerimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Requerimiento1ActionPerformed(evt);
            }
        });
        Ventanas.add(Requerimiento1);

        Requerimiento2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Requerimiento2.setLabel("Requerimiento2");
        Requerimiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Requerimiento2ActionPerformed(evt);
            }
        });
        Ventanas.add(Requerimiento2);

        Requerimiento3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Requerimiento3.setLabel("Requerimiento3");
        Requerimiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Requerimiento3ActionPerformed(evt);
            }
        });
        Ventanas.add(Requerimiento3);

        MenuBar.add(Ventanas);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Requerimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Requerimiento1ActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_Requerimiento1ActionPerformed

    private void Requerimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Requerimiento2ActionPerformed
        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_Requerimiento2ActionPerformed

    private void Requerimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Requerimiento3ActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_Requerimiento3ActionPerformed
  
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        if(JOptionPane.showConfirmDialog(this,"¿Desea cerrar la aplicación?",
                getTitle(), JOptionPane.YES_OPTION)== JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_SalirActionPerformed

private void ListarRegistros1(){
    try {
        var requ1 = controlador.consultarRequerimiento1();
        reque1_TM = new Requerimiento1_TM(requ1);
        tblRegistros1.setModel(reque1_TM);
    } catch (Exception e) {
    }
} 
private void ListarRegistros2(){
    try {
        var requ2 = controlador.consultarRequerimiento2();
        reque2_TM = new Requerimiento2_TM(requ2);
        tblRegistros2.setModel(reque2_TM);
    } catch (Exception e) {
    }
}

private void ListarRegistros3(){
    try {
        var requ3 = controlador.consultarRequerimiento3();
        reque3_TM = new Requerimiento3_TM(requ3);
        tblRegistros3.setModel(reque3_TM);
    } catch (Exception e) {
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requerimientos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requerimientos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requerimientos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requerimientos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Requerimientos_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem Requerimiento1;
    private javax.swing.JMenuItem Requerimiento2;
    private javax.swing.JMenuItem Requerimiento3;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu Ventanas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pReque1;
    private javax.swing.JPanel pReque2;
    private javax.swing.JPanel pReque3;
    private javax.swing.JTable tblRegistros1;
    private javax.swing.JTable tblRegistros2;
    private javax.swing.JTable tblRegistros3;
    private javax.swing.JTabbedPane tpPrincipal;
    // End of variables declaration//GEN-END:variables
}
